#!/bin/sh -e

# Downloads and unpacks Ubuntu mini.iso fixing lack of UEFI support
# See https://bugs.launchpad.net/ubuntu/+source/debian-installer/+bug/1429030
# Thanks to https://www.nemotos.net/?p=2057

! [ $# -eq 1 ] && {
  echo "Usage: $0 <codename>"
  exit 1
}

codename=$1
url=http://archive.ubuntu.com/ubuntu/dists/${codename}/main/installer-amd64/current/images/netboot/mini.iso

temp=$(mktemp mini.XXXXXXXXXX.iso)
trap 'rm -f "$temp"' EXIT

curl -o "$temp" "$url"

md5sum -- "$temp"
sha1sum -- "$temp"

7z x -o"$codename" "$temp"
7z x -o"$codename" "$codename/boot/grub/efi.img"
