#!/bin/sh

current_user=`id -un "$1"`

while IFS=':' read user _; do
  if [ "$user" != "$current_user" ]; then
    continue
  fi

  dm_crypt_name=home_$user
  user_home=`getent passwd "$user" | cut -f6 -d:`
  
  if systemctl is-active "$user_home"; then
    systemctl stop "$user_home"
  fi
  
  if cryptsetup status "$dm_crypt_name" > /dev/null; then
    cryptsetup close "$dm_crypt_name"
  fi

  exit $?
done < /usr/local/etc/mnthome.conf

exit 0
